package com.example.mienspa.models;
// Generated Oct 24, 2022, 4:46:04 PM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProductImages generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "product_images", catalog = "mienspa3")
public class ProductImages implements java.io.Serializable {

	private Integer id;
	private Product product;
	private String imgPath;
	private Date createdAt;

	public ProductImages() {
	}

	public ProductImages(Product product, String imgPath) {
		this.product = product;
		this.imgPath = imgPath;
	}

	public ProductImages(Product product, String imgPath, Date createdAt) {
		this.product = product;
		this.imgPath = imgPath;
		this.createdAt = createdAt;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_id", nullable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Column(name = "img_path", nullable = false, length = 150)
	public String getImgPath() {
		return this.imgPath;
	}

	public void setImgPath(String imgPath) {
		this.imgPath = imgPath;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

}
