package com.example.mienspa.models;
// Generated Oct 24, 2022, 4:46:04 PM by Hibernate Tools 4.3.6.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Product generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "product", catalog = "mienspa3")
public class Product implements java.io.Serializable {

	private String proId;
	private Category category;
	private String proName;
	private BigDecimal proPrice;
	private String featureImgPath;
	private String proContent;
	private String proBrand;
	private Date createdAt;
	private Date updatedAt;
	private Boolean isDelete;
	private Set<ProductImages> productImageses = new HashSet<ProductImages>(0);
	private Set<OrdersProDetail> ordersprodetails = new HashSet<OrdersProDetail>(0);

	public Product() {
	}

	public Product(String proId, Category category, String proName, BigDecimal proPrice, String proContent,
			String proBrand) {
		this.proId = proId;
		this.category = category;
		this.proName = proName;
		this.proPrice = proPrice;
		this.proContent = proContent;
		this.proBrand = proBrand;
	}

	public Product(String proId, Category category, String proName, BigDecimal proPrice, String featureImgPath,
			String proContent, String proBrand, Date createdAt, Date updatedAt, Boolean isDelete,
			Set<ProductImages> productImageses, Set<OrdersProDetail> ordersprodetails) {
		this.proId = proId;
		this.category = category;
		this.proName = proName;
		this.proPrice = proPrice;
		this.featureImgPath = featureImgPath;
		this.proContent = proContent;
		this.proBrand = proBrand;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.isDelete = isDelete;
		this.productImageses = productImageses;
		this.ordersprodetails = ordersprodetails;
	}

	@Id

	@Column(name = "pro_id", unique = true, nullable = false, length = 128)
	public String getProId() {
		return this.proId;
	}

	public void setProId(String proId) {
		this.proId = proId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "category_id", nullable = false)
	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	@Column(name = "pro_name", nullable = false)
	public String getProName() {
		return this.proName;
	}

	public void setProName(String proName) {
		this.proName = proName;
	}

	@Column(name = "pro_price", nullable = false)
	public BigDecimal getProPrice() {
		return this.proPrice;
	}

	public void setProPrice(BigDecimal proPrice) {
		this.proPrice = proPrice;
	}

	@Column(name = "feature_img_path")
	public String getFeatureImgPath() {
		return this.featureImgPath;
	}

	public void setFeatureImgPath(String featureImgPath) {
		this.featureImgPath = featureImgPath;
	}

	@Column(name = "pro_content", nullable = false)
	public String getProContent() {
		return this.proContent;
	}

	public void setProContent(String proContent) {
		this.proContent = proContent;
	}

	@Column(name = "pro_brand", nullable = false)
	public String getProBrand() {
		return this.proBrand;
	}

	public void setProBrand(String proBrand) {
		this.proBrand = proBrand;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", length = 19)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@Column(name = "isDelete")
	public Boolean getIsDelete() {
		return this.isDelete;
	}

	public void setIsDelete(Boolean isDelete) {
		this.isDelete = isDelete;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<ProductImages> getProductImageses() {
		return this.productImageses;
	}

	public void setProductImageses(Set<ProductImages> productImageses) {
		this.productImageses = productImageses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<OrdersProDetail> getOrdersprodetails() {
		return this.ordersprodetails;
	}

	public void setOrdersprodetails(Set<OrdersProDetail> ordersprodetails) {
		this.ordersprodetails = ordersprodetails;
	}

}
