package com.example.mienspa.models;
// Generated Oct 24, 2022, 4:46:04 PM by Hibernate Tools 4.3.6.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Serce generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "serce", catalog = "mienspa3")
public class Serce implements java.io.Serializable {

	private String seId;
	private String seName;
	private BigDecimal sePrice;
	private String seDescription;
	private String seNote;
	private Boolean seTurnOn;
	private Date createdAt;
	private Date updatedAt;
	private Boolean isDelete;
	private String seImage;
	
	private Set<OrderSerDetail> orderserdetails = new HashSet<OrderSerDetail>(0);

	public Serce() {
	}

	public Serce(String seId, String seName, BigDecimal sePrice, String seDescription) {
		this.seId = seId;
		this.seName = seName;
		this.sePrice = sePrice;
		this.seDescription = seDescription;
	}

	public Serce(String seId, String seName, BigDecimal sePrice, String seDescription, String seNote, Boolean seTurnOn,
			Date createdAt, Date updatedAt, Boolean isDelete, Set<OrderSerDetail> orderserdetails) {
		this.seId = seId;
		this.seName = seName;
		this.sePrice = sePrice;
		this.seDescription = seDescription;
		this.seNote = seNote;
		this.seTurnOn = seTurnOn;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.isDelete = isDelete;
		this.orderserdetails = orderserdetails;
	}

	@Id

	@Column(name = "se_Id", unique = true, nullable = false, length = 128)
	public String getSeId() {
		return this.seId;
	}

	public void setSeId(String seId) {
		this.seId = seId;
	}

	@Column(name = "se_Name", nullable = false, length = 65535)
	public String getSeName() {
		return this.seName;
	}

	public void setSeName(String seName) {
		this.seName = seName;
	}

	@Column(name = "se_Price", nullable = false, precision = 9, scale = 3)
	public BigDecimal getSePrice() {
		return this.sePrice;
	}

	public void setSePrice(BigDecimal sePrice) {
		this.sePrice = sePrice;
	}

	@Column(name = "se_Description", nullable = false, length = 65535)
	public String getSeDescription() {
		return this.seDescription;
	}

	public void setSeDescription(String seDescription) {
		this.seDescription = seDescription;
	}

	@Column(name = "se_Note", length = 65535)
	public String getSeNote() {
		return this.seNote;
	}

	public void setSeNote(String seNote) {
		this.seNote = seNote;
	}

	@Column(name = "se_TurnOn")
	public Boolean getSeTurnOn() {
		return this.seTurnOn;
	}

	public void setSeTurnOn(Boolean seTurnOn) {
		this.seTurnOn = seTurnOn;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", length = 19)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@Column(name = "isDelete")
	public Boolean getIsDelete() {
		return this.isDelete;
	}

	public void setIsDelete(Boolean isDelete) {
		this.isDelete = isDelete;
	}

	@Column(name = "se_Image", length = 250)
	public String getSeImage() {
		return seImage;
	}

	public void setSeImage(String seImage) {
		this.seImage = seImage;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "serce")
	public Set<OrderSerDetail> getOrderserdetails() {
		return this.orderserdetails;
	}

	public void setOrderserdetails(Set<OrderSerDetail> orderserdetails) {
		this.orderserdetails = orderserdetails;
	}

}
